# Generated by Django 5.2.8 on 2026-03-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('teen', 'Teen'), ('young_adult', 'Young Adult'), ('adult', 'Adult')], max_length=20, null=True),
        ),
    ]
